print "STR: "
print rand(3..18), ". "
print "DEX: "
print rand(3..18), ". "
print "CON: "
print rand(3..18), ". "
print "INT: "
print rand(3..18), ". "
print "WIS: "
print rand(3..18), ". "
print "CHR: "
print rand(3..18), ". "
